name: Auto Update Prom Feed

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run script
      run: python -u mixer.py

    - name: Commit and Push changes
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add prom_full_auto_feed.xml
        git commit -m "Автоматичне оновлення залишків та цін" || exit 0
        git push
